language: python
python:
  - "2.7"
install:
    - pip install -r requirements.txt
    - travis/install_ecl.sh

env:
  global:
    - DJANGO_SETTINGS_MODULE=fmu_storage.settings
    - DATABASE_URL=sqlite:////$TRAVIS_BUILD_DIR/db.sqlite
    - STORAGE_ROOT=$TRAVIS_BUILD_DIR/storage
    - PYTHONPATH=$TRAVIS_BUILD_DIR/install/lib/python2.7/dist-packages:$PYTHONPATH

script:
    - python manage.py test
