# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_name', models.CharField(max_length=132)),
                ('content', models.FileField(upload_to='%Y/%m/%d')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('owner_group', models.CharField(default=None, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('basefile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulation.BaseFile')),
            ],
            bases=('simulation.basefile',),
        ),
        migrations.CreateModel(
            name='GridFile',
            fields=[
                ('basefile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulation.BaseFile')),
            ],
            bases=('simulation.basefile',),
        ),
        migrations.CreateModel(
            name='InitFile',
            fields=[
                ('basefile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulation.BaseFile')),
            ],
            bases=('simulation.basefile',),
        ),
        migrations.CreateModel(
            name='RestartFile',
            fields=[
                ('basefile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulation.BaseFile')),
            ],
            bases=('simulation.basefile',),
        ),
        migrations.AddField(
            model_name='summary',
            name='smspec_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smspec_file', to='simulation.BaseFile'),
        ),
        migrations.AddField(
            model_name='summary',
            name='unsmry_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unsmry_file', to='simulation.BaseFile'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.Summary'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.Simulation'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulation.DataFile'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='grid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulation.GridFile'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='init',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulation.InitFile'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='restart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulation.RestartFile'),
        ),
    ]
